### ISSUE TITLE
Poor load balancing computing stellar densities

### ISSUE THREAD

**Issue by sbird** [MP-Gadget/MP-Gadget#501]
The Wait time for the stellar density treewalk is very long, perhaps 10x the compute time. Why is this?

**Comment by sbird** [comment]
Looks like NumNgb can become very large in some cases - probably this is why it becomes slow: 
it is reading a lot on other processors.

[ 000208.94 ] Task 1: Max numngb 118.071 (hsml 5.27796) min numngb 108.21 (hsml 3.94778)
[ 000208.94 ] Task 2: Max numngb 118.096 (hsml 3.51148) min numngb 95.7821 (hsml 5.25966)
[ 000210.52 ] Task 3: Max numngb 2622.16 (hsml 8.62495) min numngb 2.34607 (hsml 7.32834)
[ 000210.52 ] Task 0: Max numngb 1140.12 (hsml 7.98913) min numngb 0.153207 (hsml 4.18032)
[ 000210.52 ] Task 1: Max numngb 1025.51 (hsml 9.42323) min numngb 2.33558 (hsml 5.46565)
[ 000210.52 ] Task 2: Max numngb 1132.1 (hsml 4.88991) min numngb 1.79942 (hsml 5.4202)
[ 000210.53 ] Task 3: Max numngb 1499.65 (hsml 6.8452) min numngb 11.1529 (hsml 9.23371)
[ 000210.53 ] Task 1: Max numngb 541.771 (hsml 7.47876) min numngb 12.5501 (hsml 6.88672)
[ 000210.53 ] Task 0: Max numngb 680.075 (hsml 6.34058) min numngb 2.45534 (hsml 5.26721)
[ 000210.53 ] Task 2: Max numngb 648.004 (hsml 3.88088) min numngb 10.18 (hsml 6.82945)
[ 000210.54 ] Task 3: Max numngb 792.335 (hsml 5.4327) min numngb 39.7395 (hsml 11.6345)
[ 000210.54 ] Task 0: Max numngb 387.258 (hsml 5.03221) min numngb 13.9725 (hsml 6.63668)
[ 000210.54 ] Task 1: Max numngb 287.294 (hsml 5.93552) min numngb 44.5018 (hsml 8.67727)
[ 000210.54 ] Task 2: Max numngb 359.313 (hsml 3.08007) min numngb 23.3526 (hsml 8.02315)
[ 000210.54 ] Task 3: Max numngb 383.556 (hsml 4.31619) min numngb 84.0151 (hsml 7.39249)
[ 000210.54 ] Task 0: Max numngb 206.827 (hsml 4.25135) min numngb 50.1302 (hsml 8.30348)

**Comment by sbird** [comment]
[ 000555.42 ] Task 3: Max numngb 1610 (hsml 6.85025) min numngb 0.815979 (hsml 4.21211)
[ 000555.42 ] Task 0: Max numngb 5728.53 (hsml 9.31379) min numngb 1.80382 (hsml 5.37362)
[ 000555.42 ] Task 2: Max numngb 2079.18 (hsml 8.34859) min numngb 0.002935 (hsml 3.42667)**

**Comment by rainwoodman** [comment]
Stars can be a lot more clumpy than gas. (It is not really an SPH).

What about using distance to k-th neighbour as a proxy for density rather than actually converging it?
Depending on how stellar density is used downstream the k-nn 'density' may be good enough.

I don't think we have implemented the algorithm to quickly compute distance to k-nn; but at least if we put that in place it should be faster than the hsml iteration.

**Comment by sbird** [comment]
We need the density to normalise the amount of metals returned from the stars. We pick hsml so that it returns to about 100 particles. The factor we especially need is the total volume of neighbours, which we can't get another way (although it only needs one loop). We could try to use the hsml of the nearest gas particle as a 'seed' though.

The other solution I had was to just do stellar density every timestep so it doesn't have time to get too wrong.

**Comment by sbird** [comment]
Can we get hsml by doing:
no = force_get_father()
loop over children of no for a gas particle ?

**Comment by sbird** [comment]
Doing that doesn't seem to work much better. I am just going to constantly update stellar hsml.

**Comment by sbird** [comment]
Still does not work...some star particles have seriously bad NumNgb estimates on first run. I guess their timesteps are getting too long, since they are gravitational.

**Comment by sbird** [comment]
@rainwoodman: I think I do not understand your comment about distance to kth neighbour: Isn't that exactly what Hsml is already?

**Comment by rainwoodman** [comment]
It is similar but different. 

- The Hsml iterations compute scales HSML, such that the sum of the SPH kernels inside Hsml equals DesNgb with very low variance. 
- The distance to the k-th neighbour knows nothing about the SPH kernels, and needs no such iterations. The expected the total sum of the SPH kernels near a particle is ~ <n> * Hsml**3, but the variance is larger.

I have the impression that because density gradient that shows up in the SPH equations, it is important to require the error to be uniformly bound per particle. 

However, as we don't use the gradient of the stellar density field, an 'effective' density computed from distance to the k-th neighbour could be good enough. I think we use that for visualization of stars and DMs already in notebooks.
People do estimate the PDF density with distance to k-nn for computing KL divergence from samples for example.

Another background: in Gadget there was a module that computes Hsml for DM particles (in subfind). I think the reason behind that module was more to reuse the only existing code to estimate a density than necessity. I don't think Gadget has an implementation of distance to k-nn yet, even though it should be much easier than the density iteration.

**Comment by sbird** [comment]
I see - do you have a link to the algorithm? Does it return the kth nearest neighbours or the distance to them? We indeed really just need to touch k nearest neighbours twice.

**Comment by sbird** [comment]
Looking it up that seems indeed to be exactly what we want: https://gopalcdas.com/2017/05/24/construction-of-k-d-tree-and-using-it-for-nearest-neighbour-search/ We form a heap and expel elements from it. Some modification of treewalk may be necessary so that we can do the closest domain first.

**Comment by rainwoodman** [comment]
Yes. As long as any tree node is bounding all of its descendants, this should work -- kdtree is not a requirement. 
It is pretty standard to use a heap there. Here is an implementation inside scipy:

https://github.com/scipy/scipy/blob/master/scipy/spatial/ckdtree/src/query.cxx

If a node is further than heap_last and len(heap) == k, then there is no need to open it. 
How to deal with ghosts? If a particle is exported to multiple ranks I am not sure what we can do. Probably keep all k neighours on all ranks and then do a merge during reduce?

**Comment by sbird** [comment]
I was thinking about this last night: I think it comes down to the order in which we walk the tree. If we have a good initial guess for the k nearest neighbours we will not usually have to export to multiple ranks. On the other hand, if we have no initial guess we will. So my proposed treewalk order is:
1. Fill the heap with the k particles nearest the current target (ie, for particle i, find i->i+k gas particles). The particle table is close to Peano Hilbert so this should usually not be a terrible guess.
2. Walk the tree *starting from the topnode parent* until we reach another topnode. This will refine our initial guess to include k particles in the current topnode and should produce a heap which is close to the k nearest neighbours.
3. Walk the tree from the top again, skipping the current topnode. This should hopefully let us cull most other topnodes for most particles immediately.

What do you think?

**Comment by sbird** [comment]
This did not really help...nice idea though!

**Comment by sbird** [comment]
Oops, meant to close the PR

**Comment by sbird** [comment]
Not entirely solved by https://github.com/MP-Gadget/MP-Gadget/pull/509 but much better now.
